spring:
  application:
    name: spring-cloud-example-config
  profiles:
    active: native #启用本地配置文件
#  security:
#    user:
#      name: user
#      password: 123456
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs/ #配置文件扫描目录

server:
  port: 8000